language: cpp

cache: apt

compiler:
    - gcc
    - clang

env:
    global:
        - MAKEFLAGS="-j2"
    matrix:
        - QT_BASE=48
        - QT_BASE=50
        - QT_BASE=51
        - QT_BASE=52
        - QT_BASE=53
        - QT_BASE=54
        - QT_BASE=55

sudo: required

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - if [ "$QT_BASE" = "50" ]; then sudo add-apt-repository ppa:beineri/opt-qt502 -y; fi
    - if [ "$QT_BASE" = "51" ]; then sudo add-apt-repository ppa:beineri/opt-qt511 -y; fi
    - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521 -y; fi
    - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
    - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542 -y; fi
    - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
    - sudo apt-get update -qq
    - ./travis_install_capstone.sh

install:
    - if [ "$QT_BASE" = "48" ]; then sudo apt-get install -qq qt4-qmake libqt4-gui libqt4-core libqt4-dev; fi
    - if [ "$QT_BASE" = "50" ]; then sudo apt-get install -qq qtbase  qtxmlpatterns; source /opt/qt5/bin/qt5-env.sh; fi
    - if [ "$QT_BASE" = "51" ]; then sudo apt-get install -qq qt51base qt51xmlpatterns; source /opt/qt51/bin/qt51-env.sh; fi
    - if [ "$QT_BASE" = "52" ]; then sudo apt-get install -qq qt52base qt52xmlpatterns; source /opt/qt52/bin/qt52-env.sh; fi
    - if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base qt53xmlpatterns; source /opt/qt53/bin/qt53-env.sh; fi
    - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base qt54xmlpatterns; source /opt/qt54/bin/qt54-env.sh; fi
    - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base qt55xmlpatterns; source /opt/qt55/bin/qt55-env.sh; fi

before_script:
    - if [ "$CXX" = "clang++" ] && [ "$QT_BASE" == "48" ]; then qmake -spec unsupported/linux-clang CONFIG+=warn_off QMAKE_CXXFLAGS+='-isystem /usr/include/qt4 -Wall -Wextra -Wno-missing-braces'; fi
    - if [ "$CXX" = "clang++" ] && [ "$QT_BASE" != "48" ]; then qmake -spec linux-clang; fi
    - if [ "$CXX" != "clang++" ]; then qmake; fi

script:
    - if [ "$CXX" = "clang++" ] && [ "$QT_BASE" == "48" ]; then make; fi
    - if [ "$CXX" = "clang++" ] && [ "$QT_BASE" != "48" ]; then /bin/true; fi
    - if [ "$CXX" != "clang++" ]; then make; fi

branches:
    only:
        - master

os:
    - linux

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libboost-dev
            - gcc-4.8
            - g++-4.8
